//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyffUniverseLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyffUniverseLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a profile before launching the game..
        /// </summary>
        internal static string FUL_playButton_no_profile_selected {
            get {
                return ResourceManager.GetString("FUL_playButton_no_profile_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile selected.
        /// </summary>
        internal static string FUL_playButton_no_profile_selected_caption {
            get {
                return ResourceManager.GetString("FUL_playButton_no_profile_selected_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile selected does not exist. Please select one from the profil [rest of string was truncated].
        /// </summary>
        internal static string FUL_playButton_selected_profile_does_not_exist {
            get {
                return ResourceManager.GetString("FUL_playButton_selected_profile_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile selected does not exist.
        /// </summary>
        internal static string FUL_playButton_selected_profile_does_not_exist_caption {
            get {
                return ResourceManager.GetString("FUL_playButton_selected_profile_does_not_exist_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile successfully saved!.
        /// </summary>
        internal static string FULNP_saveButton_success {
            get {
                return ResourceManager.GetString("FULNP_saveButton_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string FULNP_saveButton_success_caption {
            get {
                return ResourceManager.GetString("FULNP_saveButton_success_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the height.
        /// </summary>
        internal static string FULNP_saveButton_invalidHeight {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height.
        /// </summary>
        internal static string FULNP_saveButton_invalidHeight_caption {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidHeight_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the width.
        /// </summary>
        internal static string FULNP_saveButton_invalidWidth {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width.
        /// </summary>
        internal static string FULNP_saveButton_invalidWidth_caption {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidWidth_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid window width or height for the new profile.  If y [rest of string was truncated].
        /// </summary>
        internal static string FULNP_saveButton_invalidWidthAndHeight {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidWidthAndHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window width or height missing.
        /// </summary>
        internal static string FULNP_saveButton_invalidWidthAndHeight_caption {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidWidthAndHeight_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new profile.
        /// </summary>
        internal static string FULNP_saveButton_invalidUsername {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name missing.
        /// </summary>
        internal static string FULNP_saveButton_invalidUsername_caption {
            get {
                return ResourceManager.GetString("FULNP_saveButton_invalidUsername_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Are you sure you want to delete the profile '$USERNAME$'?.
        /// </summary>
        internal static string FUL_manageProfile_deleteProfileButton_confirmation {
            get {
                return ResourceManager.GetString("FUL_manageProfile_deleteProfileButton_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the profile '$USERNAME$'?.
        /// </summary>
        internal static string FUL_manageProfile_deleteProfileButton_confirmation_caption {
            get {
                return ResourceManager.GetString("FUL_manageProfile_deleteProfileButton_confirmation_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That profile does not exist. Please select a different one..
        /// </summary>
        internal static string FUL_selectUserInput_profileDoesNotExist {
            get {
                return ResourceManager.GetString("FUL_selectUserInput_profileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile doesn't exist.
        /// </summary>
        internal static string FUL_selectUserInput_profileDoesNotExist_caption {
            get {
                return ResourceManager.GetString("FUL_selectUserInput_profileDoesNotExist_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile with that name already exists. Please select a different one [rest of string was truncated].
        /// </summary>
        internal static string FUL_manageProfileSaveButton_profileAlreadyExists {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_profileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile already exists.
        /// </summary>
        internal static string FUL_manageProfileSaveButton_profileAlreadyExists_caption {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_profileAlreadyExists_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! The selected profile could not be found. A new p [rest of string was truncated].
        /// </summary>
        internal static string FUL_manageProfileSaveButton_oldProfile_doesNotExist {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_oldProfile_doesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string FUL_manageProfileSaveButton_oldProfile_doesNotExist_caption {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_oldProfile_doesNotExist_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile changes saved succesfully!.
        /// </summary>
        internal static string FUL_manageProfileSaveButton_success {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string FUL_manageProfileSaveButton_success_caption {
            get {
                return ResourceManager.GetString("FUL_manageProfileSaveButton_success_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyff Model Viewer.
        /// </summary>
        internal static string FULW_flyffModelViewerMenuItem {
            get {
                return ResourceManager.GetString("FULW_flyffModelViewerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh client.
        /// </summary>
        internal static string FULW_frozenGameMenuItem {
            get {
                return ResourceManager.GetString("FULW_frozenGameMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide menu.
        /// </summary>
        internal static string FULW_HideMenuMenuItem {
            get {
                return ResourceManager.GetString("FULW_HideMenuMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string FUL_profileSettingsLabel {
            get {
                return ResourceManager.GetString("FUL_profileSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profiles.
        /// </summary>
        internal static string FUL_manageProfilesLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile or create a new one:.
        /// </summary>
        internal static string FUL_selectUserLabel {
            get {
                return ResourceManager.GetString("FUL_selectUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string FUL_playButton {
            get {
                return ResourceManager.GetString("FUL_playButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Profile.
        /// </summary>
        internal static string FUL_createNewProfileButton {
            get {
                return ResourceManager.GetString("FUL_createNewProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher language.
        /// </summary>
        internal static string FUL_language_label {
            get {
                return ResourceManager.GetString("FUL_language_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Tsadriu Powered by Microsoft WebView2.
        /// </summary>
        internal static string FUL_credit_label {
            get {
                return ResourceManager.GetString("FUL_credit_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profile to modify:.
        /// </summary>
        internal static string FUL_manageProfiles_selectProfileToModifyLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_selectProfileToModifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string FUL_manageProfiles_profileNameLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_profileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred width.
        /// </summary>
        internal static string FUL_manageProfiles_preferredWidthLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_preferredWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred height.
        /// </summary>
        internal static string FUL_manageProfiles_preferredHeightLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_preferredHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen?.
        /// </summary>
        internal static string FUL_manageProfiles_fullscreenLabel {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_fullscreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt to screen size.
        /// </summary>
        internal static string FUL_manageProfiles_adaptToScreenSizeButton {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_adaptToScreenSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string FUL_manageProfiles_saveChangesButton {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_saveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this profile.
        /// </summary>
        internal static string FUL_manageProfiles_deleteProfileButton {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_deleteProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all profiles.
        /// </summary>
        internal static string FUL_manageProfiles_deleteAllProfilesButton {
            get {
                return ResourceManager.GetString("FUL_manageProfiles_deleteAllProfilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the program when the profile is launched..
        /// </summary>
        internal static string FULNP_preferredWidthLabel_tooltip {
            get {
                return ResourceManager.GetString("FULNP_preferredWidthLabel_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the program when the profile is launched..
        /// </summary>
        internal static string FULNP_preferredHeightLabel_tooltip {
            get {
                return ResourceManager.GetString("FULNP_preferredHeightLabel_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it's checked, when the profile is launched, the window will be at f [rest of string was truncated].
        /// </summary>
        internal static string FULNP_fullscreenLabel_tooltip {
            get {
                return ResourceManager.GetString("FULNP_fullscreenLabel_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sure about the width and/or height of your screen? Press this butt [rest of string was truncated].
        /// </summary>
        internal static string FULNP_adaptScreenSize_tooltip {
            get {
                return ResourceManager.GetString("FULNP_adaptScreenSize_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        internal static string FULNP_saveButton {
            get {
                return ResourceManager.GetString("FULNP_saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while loading the launcher properties. A log file [rest of string was truncated].
        /// </summary>
        internal static string FUL_launcherPropertiesJson_error {
            get {
                return ResourceManager.GetString("FUL_launcherPropertiesJson_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher settings error.
        /// </summary>
        internal static string FUL_launcherPropertiesJson_error_caption {
            get {
                return ResourceManager.GetString("FUL_launcherPropertiesJson_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Are you sure you want to delete all profiles?.
        /// </summary>
        internal static string FUL_manageProfile_deleteAllProfilesButton_confirmation {
            get {
                return ResourceManager.GetString("FUL_manageProfile_deleteAllProfilesButton_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all profiles?.
        /// </summary>
        internal static string FUL_manageProfile_deleteAllProfilesButton_confirmation_caption {
            get {
                return ResourceManager.GetString("FUL_manageProfile_deleteAllProfilesButton_confirmation_caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open data folder.
        /// </summary>
        internal static string FUL_dataFolderButton {
            get {
                return ResourceManager.GetString("FUL_dataFolderButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The launcher saves all of its files (profiles, settings, browser dat [rest of string was truncated].
        /// </summary>
        internal static string FUL_dataFolderButton_tooltip {
            get {
                return ResourceManager.GetString("FUL_dataFolderButton_tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The launcher files have been moved to a new location. [rest of string was truncated].
        /// </summary>
        internal static string FUL_migration_message {
            get {
                return ResourceManager.GetString("FUL_migration_message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launcher files moved.
        /// </summary>
        internal static string FUL_migration_message_caption {
            get {
                return ResourceManager.GetString("FUL_migration_message_caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select or type a profile.
        /// </summary>
        internal static string FUL_selectUserInput_watermark {
            get {
                return ResourceManager.GetString("FUL_selectUserInput_watermark", resourceCulture);
            }
        }
    }
}
